### ISSUE TITLE
Edward

### ISSUE THREAD

**Issue by matthew4444** [NetherManiacsKingdom/SAM-BETA#6]
Click here https://gitter.im/matthew4444/NethermaniacsKingdom

**Comment by Edwardthedog2** [comment]
Sorry, it won't let me visit Gitter. Probably because I'm at school on my school chromebook. When I get home I will.

**Comment by matthew4444** [comment]
Ok then lets talk here

**Comment by matthew4444** [comment]
do u know how to make mariokart in pocketmine

**Comment by matthew4444** [comment]
hey

**Comment by Edwardthedog2** [comment]
No, I'm afraid I don't know how. Sorry

**Comment by matthew4444** [comment]
hey

**Comment by matthew4444** [comment]
R u on

**Comment by Edwardthedog2** [comment]
Yeah

**Comment by matthew4444** [comment]
Hey

**Comment by matthew4444** [comment]
r u away from school now

**Comment by matthew4444** [comment]
hey i got a new gitter link
Http://gitter.im/matthew4444/NetherManiacsKingdom

**Comment by Edwardthedog2** [comment]
No I'm still at school. But I only have 20 more minutes. Less actually. Soon I'll be on the bus home.

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
hope u like the new gitter page

**Comment by matthew4444** [comment]
And like the new name of the team

**Comment by Edwardthedog2** [comment]
Yeah, I like the new team name. Gitter is blocked at school though because its for chatting. That one I'll have to wait and see.

**Comment by matthew4444** [comment]
Ok i made it up

**Comment by matthew4444** [comment]
I like ur login plugins also

**Comment by Edwardthedog2** [comment]
Oh cool. Yeah as soon as I'm on the bus home with my phone ill check out the gitter page.

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
Look at ur sam plugin readme now

**Comment by Edwardthedog2** [comment]
Aww, thank you

**Comment by matthew4444** [comment]
Np and now look

**Comment by Edwardthedog2** [comment]
Look at what?

**Comment by matthew4444** [comment]
Look under the word Code

**Comment by Edwardthedog2** [comment]
Oh I see it now. Thanks

**Comment by matthew4444** [comment]
Np

**Comment by matthew4444** [comment]
Hey email me some time if u want.

**Comment by matthew4444** [comment]
And what up

**Comment by matthew4444** [comment]
U make the best plugins also

**Comment by Edwardthedog2** [comment]
Okay, I'll email you when I can. I'm not sure if AOL (the email service I use.) Is blocked.
Thank you. I try my best at them.

**Comment by matthew4444** [comment]
ok i will also,and good luck on makin epix auth pluginz

**Comment by Edwardthedog2** [comment]
Thank you, I will need it.

**Comment by matthew4444** [comment]
Anytime,and im gona get a snack

**Comment by matthew4444** [comment]
k , when will be on glitter
